# Generated by Django 5.0.6 on 2024-06-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='fake', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
    ]
