# Generated by Django 5.0.6 on 2024-09-09 19:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='competition_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.IntegerField(choices=[(0, 'Standard'), (1, 'Final'), (2, 'Semi-Final'), (4, 'Quarter-Final'), (8, 'Round of 16'), (16, 'Round of 32'), (32, 'Round of 64'), (64, 'Round of 128')], default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='score_team1_after_ext',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='score_team2_after_ext',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='bonus_perfect',
            field=models.IntegerField(choices=[(0, 'No perfect bonus'), (10, 'Perfect bonus 10'), (20, 'Perfect bonus 20'), (50, 'Perfect bonus 50'), (100, 'Perfect bonus 100')], default=20),
        ),
        migrations.AddField(
            model_name='league',
            name='bonus_stake',
            field=models.IntegerField(choices=[(0, 'No bonus'), (1, 'Bonus Mode 1')], default=0),
        ),
        migrations.AddField(
            model_name='league',
            name='code',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.AddField(
            model_name='league',
            name='short_name',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='with_ext',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='activity_type',
            field=models.IntegerField(choices=[(0, 'Mixed'), (1001, 'Football'), (1002, 'Tennis')], default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bet',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='bet.game'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='league',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='bet.league'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='score_team1',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bet',
            name='score_team2',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='score_team1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='score_team2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='leagues_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='league',
            name='users',
            field=models.ManyToManyField(related_name='leagues_played', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together={('game', 'user', 'league')},
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=5, null=True)),
                ('activity_type', models.IntegerField(choices=[(0, 'Mixed'), (1001, 'Football'), (1002, 'Tennis')])),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cp_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bet.competition'),
        ),
        migrations.AddField(
            model_name='league',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lg_competition', to='bet.competition'),
        ),
    ]
