# Generated by Django 5.0.6 on 2024-09-09 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_game_competition_number_game_game_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='game',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='bet.game'),
        ),
    ]
