# Generated by Django 5.0.6 on 2024-09-09 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0003_alter_bet_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='bet.game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Standard'), (1, 'Final'), (2, 'Semi-Final'), (4, 'Quarter-Final'), (8, 'Round of 16'), (16, 'Round of 32'), (32, 'Round of 64'), (64, 'Round of 128')], default=0, null=True),
        ),
    ]
